name: CI pipeline

on:
  pull_request:
    branches: [main, develop]
  
  workflow_dispatch:

jobs:
    build-and-test:
      runs-on: ubuntu-latest
      
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Python 3.12
          uses: actions/setup-python@v5
          with:
            python-version: "3.12"
            cache: 'pip'

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements-api.txt
            pip install -r requirements-dev.txt

        - name: Run tests
          run: |
            pytest test/