name: CI pipeline

on:
  pull_request:
    branches: [main, develop]
  
  workflow_dispatch:

jobs:
    build-and-test:
      runs-on: ubuntu-latest
      
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Python 3.12
          uses: actions/setup-python@v5
          with:
            python-version: "3.12"
            cache: 'pip'

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements-api.txt
            pip install -r requirements-dev.txt

        - name: Check linter
          run: |
            python -m flake8 app/

        - name: Run tests
          run: |
            pytest test/

    build-and-smoke-test:
      needs: build-and-test
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Build Docker image
          uses: docker/build-push-action@v5
          with:
            context: .
            file: ./Dockerfile
            push: false
            load: true
            tags: app-test-image:latest

        - name: Run the container
          run: |
            docker rm -f api || true
            docker run -d --name api -p 8000:8000 -e MODEL_PATH="models/model_gbost.pkl" -e APP_NAME="Food Delivery Prediction" -e APP_VERSION="0.1.0" app-test-image:latest

        - name: Wait for container to start
          run: sleep 10

        - name: Perform smoke test
          run: |
            curl --retry 5 --retry-delay 2 -f http://localhost:8000/health || exit 1
        
        - name: Show container logs on failure
          if: failure()
          run: docker logs api